### ISSUE TITLE
Rename RiscV traits and structs

### ISSUE THREAD

**Issue by aborg-dev** [near/wasmtime#19]
```[tasklist]
### Tasks
- [x] RiscvFlags
- [x] Riscv64MachineDeps
- [x] Riscv64Backend
```

**Comment by akashin** [comment]
The Rust classes are renamed now, but we still have [~137 instances](https://github.com/search?type=code&q=org%3Anear++%22rv_%22+repo%3Anear%2Fwasmtime+path%3Acranelift%2Fcodegen%2Fsrc%2Fisa%2Fzkasm) of `rv_*` rules in the inst.isle and lower.isle.
So far the strategy was to introduce `zk_*` rules instead, e.g. we have `zk_add`, `zk_mul` and `zk_div`.
I think we should finish this migration after removing the ISLE rules that we don't need.

**Comment by nagisa** [comment]
>  So far the strategy was to introduce zk_* rules instead, e.g. we have zk_add, zk_mul and zk_div. I think we should finish this migration after removing the ISLE rules that we don't need.

So far my experience is that `isle` files don’t strictly need to implement lowering rules for all of the different clift instructions (I’m not quite sure what happens if there is a clift instruction that does not have a lowering rule… I imagine a panic probably) so I’ve been removing some of these bit-by-bit in PRs like https://github.com/near/wasmtime/pull/76 and https://github.com/near/wasmtime/pull/48.

I also found that writing zkasm lowering rules from scratch is slightly easier than trying to follow or fit these rules into the framework established by risc-v backend (in retrospective, basing upon risc-v backend was a mistake even if it helped us to see generated code sooner)

One more difficult part that remains is https://github.com/near/wasmtime/issues/44 which is blocked by those rv_* rules as they introduce dependencies on e.g. the x0 (zero register) which zkasm does not have. So one way or another we want to just nuke them (rather than replace.)

**Comment by nagisa** [comment]
(Why haven’t I wholesale done that quite yet? Well, I’m still threading carefully and trying to not accidentally break everything… but so far I think it might be the case that we can just remove a bunch of the stuff straight away)

**Comment by akashin** [comment]
Marking this as done, the work on ISLE rule renaming will be done incrementally, as we touch more and more of them.
