### ISSUE TITLE
Question about filetests.

### ISSUE THREAD

**Issue by MCJOHN974** [near/wasmtime#198]
I added small logging line into the ``run_test`` function in ``filtests/src/test_run.rs`` the following way:

```
fn run_test(
    testfile: &CompiledTestFile,
    func: &ir::Function,
    context: &Context,
) -> anyhow::Result<()> {
    println!("Run test, isa = {:#?}", context.isa.unwrap());
    // old run_test function body
}
```
Than, I left ``filetests/filetests/runtests/arithmetic.clif`` file untouched, and, it's header is:
```
test interpret
test run
target aarch64
target s390x
target x86_64
target riscv64 has_m
target riscv64 has_c has_zcb
```

Than, I runned this runtest next way:
```bash
cargo run -- test filetests/filetests/runtests/arithmetic.clif
```

And, my log printed a couple of lines (~20-30), but all lines was the same, with same isa and look next way:
```
Run test, isa = TargetIsa { triple: Triple { architecture: X86_64, vendor: Unknown, operating_system: Unknown, environment: Unknown, binary_format: Unknown }, pointer_width: U64}
```

Such behavior brakes a bit my understanding about what the header of runtest mean. I was thinking line ``target <somename>`` in header means that runtest will be runned on this architecture as well.

Does this header lines really mean something different? Or maybe I use wrong command to run the  test?

**Comment by MCJOHN974** [comment]
@akashin maybe you know something about it?

**Comment by akashin** [comment]
> Such behavior brakes a bit my understanding about what the header of runtest mean. I was thinking line target <somename> in header means that runtest will be runned on this architecture as well.

Yes, but for runtests, your machine needs to support that architecture, otherwise there is no way to run the generated machine code. So I suspect the test is executed for every architecture, but it is bailing out early in https://github.com/near/wasmtime/blob/ca0d6dcefbb06ae259877cbec8b4aababa4e3134/cranelift/filetests/src/test_run.rs#L192

In my understanding, these architectures will still be tested in QEMU runs defined here https://github.com/near/wasmtime/blob/ca0d6dcefbb06ae259877cbec8b4aababa4e3134/ci/build-test-matrix.js#L94

For our purpose of testing `zkasm` target, we can't really use `test run` directly as it relies on JIT compiler under the hood that we don't implement. So we will need to define another type of test, e.g. `test zkasm` that will use JS executor instead.

**Comment by akashin** [comment]
@MCJOHN974 , I think this is resolved now? Let's close it.
